project:
  type: website

website:
  title: "Sara Colando"
  favicon: images/logo.png
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: projects.qmd
      
  page-footer:
    left:
      - text: "&copy; Copyright 2026, Scotty Dawg"
    right:
      - icon: github
        href: https://github.com/scolando/test
    background: "white"

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: darkly
    toc: true



